apiVersion: v2
name: opentelemetry-collector
<<<<<<< HEAD
version: 0.28.0
=======
version: 1.0.0
>>>>>>> 4276a57 (add upgrading example)
description: OpenTelemetry Collector Helm chart for Kubernetes
type: application
home: https://opentelemetry.io/
sources:
  - https://github.com/open-telemetry/opentelemetry-collector
  - https://github.com/open-telemetry/opentelemetry-collector-contrib
maintainers:
  - name: dmitryax
  - name: TylerHelmuth
icon: https://opentelemetry.io/img/logos/opentelemetry-logo-nav.png
appVersion: 0.58.0
